-- MerchPilot AI MVP schema (PostgreSQL)
CREATE EXTENSION IF NOT EXISTS "pgcrypto";

CREATE TABLE merchants (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), name TEXT NOT NULL, email TEXT UNIQUE NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE products (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id), sku TEXT NOT NULL, name TEXT NOT NULL, price NUMERIC(12,2), inventory_count INTEGER NOT NULL DEFAULT 0, reorder_point INTEGER NOT NULL DEFAULT 10, created_at TIMESTAMPTZ NOT NULL DEFAULT now(), UNIQUE(merchant_id, sku));
CREATE TABLE sales_history (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id), sold_on DATE NOT NULL, units INTEGER NOT NULL CHECK (units >= 0));
CREATE TABLE forecasts (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), product_id UUID NOT NULL REFERENCES products(id), horizon_days INTEGER NOT NULL DEFAULT 30, model TEXT NOT NULL DEFAULT 'chronos-bolt-mock', forecast JSONB NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE scrub_runs (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id), source_name TEXT NOT NULL, rows_received INTEGER NOT NULL, duplicates_removed INTEGER NOT NULL DEFAULT 0, warnings JSONB NOT NULL DEFAULT '[]', created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE support_threads (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id), customer_name TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'ai_active' CHECK (status IN ('ai_active','needs_human','resolved')), sentiment TEXT NOT NULL DEFAULT 'neutral', summary TEXT, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE support_messages (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), thread_id UUID NOT NULL REFERENCES support_threads(id), sender TEXT NOT NULL CHECK (sender IN ('customer','ai','merchant')), body TEXT NOT NULL, created_at TIMESTAMPTZ NOT NULL DEFAULT now());
CREATE TABLE payment_proposals (id UUID PRIMARY KEY DEFAULT gen_random_uuid(), merchant_id UUID NOT NULL REFERENCES merchants(id), kind TEXT NOT NULL CHECK (kind IN ('refund','supplier_payment')), amount_token TEXT NOT NULL, reason TEXT NOT NULL, status TEXT NOT NULL DEFAULT 'pending' CHECK (status IN ('pending','approved','rejected')), consent_token TEXT NOT NULL DEFAULT encode(gen_random_bytes(24), 'hex'), created_at TIMESTAMPTZ NOT NULL DEFAULT now(), approved_at TIMESTAMPTZ);
